### ISSUE TITLE
Caused by: org.jf.util.ExceptionWithContext: debug info items must have non-decreasing code addresses

### ISSUE THREAD

**Issue by praneshmylraj** [saswatanand/ella#11]
Information
Apktool Version (apktool -version) - 2.3.4
Operating System (Mac, Linux, Windows) - Ubuntu 16.04 LTE
APK From? (Playstore, ROM, Other) - Other
Stacktrace/Logcat
[java] Caused by: org.jf.util.ExceptionWithContext: debug info items must have non-decreasing code addresses
[java] at org.jf.dexlib2.writer.DebugWriter.writeLineNumber(DebugWriter.java:111)
[java] at org.jf.dexlib2.writer.pool.ClassPool.writeDebugItem(ClassPool.java:506)
[java] at org.jf.dexlib2.writer.DexWriter.writeDebugItem(DexWriter.java:849)
[java] at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:757)
[java] at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:214)
[java] at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:192)
[java] at org.jf.dexlib2.writer.pool.DexPool.writeTo(DexPool.java:90)
[java] at org.jf.dexlib2.DexFileFactory.writeDexFile(DexFileFactory.java:115)

Steps
Issue occurs while trying to write the instrumented[Ella https://github.com/saswatanand/ella ] file into dex again.

**Comment by nicoostendorf** [comment]
Hello, did you found a solution for this problem?
