### ISSUE TITLE
issue: Error to execute ella.i.sh <path-to-apk>

### ISSUE THREAD

**Issue by mariaifc** [saswatanand/ella#2]
Hello,

After executing ella.i.sh <path-to-apk>, I got these errors:

Maria@XXX-PC ~/Desktop/ELLA/NEW/ella-master
$ ella.i.sh com.danielfritzsch.temperatureconverter.apk
Exception in thread "main" java.io.FileNotFoundException: c:\Users\Maria\Desktop
\ELLA\NEW\ella-master\ella.settings (O sistema não pode encontrar o arquivo espe
cificado)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.apposcopy.ella.Config.load(Config.java:38)
        at com.apposcopy.ella.Main.main(Main.java:44)

Would you can help me, please?

Thanks,
Maria

**Comment by saswatanand** [comment]
You need to create the file `ella.settings` by copying `ella.settings.template` and then modifying its content to set values of various configuration variables. This is described under the heading "Before building ella" in the README.

**Comment by mariaifc** [comment]
Hi,

Thanks for your reply.

But I did it. I renamed ella.settings.template to ella.settings and modified as tutorial suggested. Please, see my ella.settings. Is there someting wrong?

####################################################
#settings required for instrumentation of dex code
####################################################
#android jar to compile (ella runtime library) against
android.jar=C:/platforms/android-21/android.jar

#path to dx tool
#OPTIONAL. If Android SDK is installed, by default ella uses
#the dx command that is in the PATH
dx=C:/build-tools/21.1.2/lib/dx

#directory where ella stores coverage data and other stuff
#OPTIONAL. The default value is "ella-out" inside the ella dir
#ella.outdir=/home/saswat/ellaoutdir

#settings used by jarsigner to sign the instrumented apk
#TODO: make these OPTIONAL. Use debug keystore
jarsigner.keystore=C:/Users/Maria/.android/debug.keystore
jarsigner.storepass=android
jarsigner.keypass=android
jarsigner.alias=androiddebugkey

############################################################
#settings required for collection of coverage data during 
#execution of instrumented app and viewing coverage report
############################################################

#tomcat settings
tomcat.dir=C:/Program Files/Apache Software Foundation/Apache Tomcat 8.0.9
tomcat.manager=admin
tomcat.password=admin

#ROOT URL
#Dont use http://localhost:8080. Instead use the IP address
#because this URL is used by the instrumented app, which is _not_
#running locally, but on the instrumentor/phone
tomcat.url=http://127.0.0.1:8080

ella.recorder=com.apposcopy.ella.runtime.MethodCoverageRecorder

Thanks,
Maria Isabel

**Comment by lazaroclapp** [comment]
Haven't tested ella on Cygwin, so I am not sure what could be the issue, but here is a thought: could you try replacing "$ELLA_DIR/ella.settings" in ella.i.sh with the Windows path to your ella.settings file (e.g. C:\Users...)?

The error seems to be that it can't find "c:\Users\Maria\Desktop\ELLA\NEW\ella-master\ella.settings", so at this point the contents of the file are not really an issue. It's just that, according to Java, there is not a file in that location (also, not very used to Windows anymore, but the fact that that path starts with lowercase c:\, instead of C:\ seems weird to me).
